/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/CoursesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/create-account`; params?: Router.UnknownInputParams; } | { pathname: `/CreateAccountScreen`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/EmergencyInstructionsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/rewards`; params?: Router.UnknownInputParams; } | { pathname: `/RewardsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/sss`; params?: Router.UnknownInputParams; } | { pathname: `/SSSScreen`; params?: Router.UnknownInputParams; } | { pathname: `/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/courses`; params?: Router.UnknownOutputParams; } | { pathname: `/CoursesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/create-account`; params?: Router.UnknownOutputParams; } | { pathname: `/CreateAccountScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/emergency-instructions`; params?: Router.UnknownOutputParams; } | { pathname: `/EmergencyInstructionsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/rewards`; params?: Router.UnknownOutputParams; } | { pathname: `/RewardsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/sss`; params?: Router.UnknownOutputParams; } | { pathname: `/SSSScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/courses${`?${string}` | `#${string}` | ''}` | `/CoursesScreen${`?${string}` | `#${string}` | ''}` | `/create-account${`?${string}` | `#${string}` | ''}` | `/CreateAccountScreen${`?${string}` | `#${string}` | ''}` | `/emergency-instructions${`?${string}` | `#${string}` | ''}` | `/EmergencyInstructionsScreen${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `/HomeScreen${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/rewards${`?${string}` | `#${string}` | ''}` | `/RewardsScreen${`?${string}` | `#${string}` | ''}` | `/sss${`?${string}` | `#${string}` | ''}` | `/SSSScreen${`?${string}` | `#${string}` | ''}` | `/WelcomeScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/courses`; params?: Router.UnknownInputParams; } | { pathname: `/CoursesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/create-account`; params?: Router.UnknownInputParams; } | { pathname: `/CreateAccountScreen`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-instructions`; params?: Router.UnknownInputParams; } | { pathname: `/EmergencyInstructionsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/rewards`; params?: Router.UnknownInputParams; } | { pathname: `/RewardsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/sss`; params?: Router.UnknownInputParams; } | { pathname: `/SSSScreen`; params?: Router.UnknownInputParams; } | { pathname: `/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
